### ISSUE TITLE
FileController -> Refactor display code to fragment for redundancy avoidance

### ISSUE THREAD

**Issue by kosch104** [hhu-propra2/abschlussprojekt-mopse#110]
Is it possible to refactor it to fragments, so we could use it in `directory` as well, or would that be over kill?

_Originally posted by @Segelzwerg in https://github.com/hhu-propra2/abschlussprojekt-mopse/pull/105_

**Comment by Segelzwerg** [comment]
Can you give a example what you want to use?

Probably we should wait with this as maybe controller will get another round of updates.

**Comment by kosch104** [comment]
Not needed anymore as files.html had redundancy and was deleted
