### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by iTitus** [hhu-propra2/abschlussprojekt-mopse#150]

**Comment by msurl** [comment]
https://www.baeldung.com/slf4j-with-log4j2-logback

Wäre jetzt die Empfehlung des Tutors :D

**Comment by Segelzwerg** [comment]
habe ich auch schon gefunden

**Comment by Segelzwerg** [comment]
> https://www.baeldung.com/slf4j-with-log4j2-logback
> 
> Wäre jetzt die Empfehlung des Tutors :D

sorry ich dachte, du bist einer aus unser Gruppe, deswegen habe ich so flappsig geantwortet. Danke für den Hinsweis!
