### ISSUE TITLE
Dataflow Violation

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#159]
https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/89355abed003d99f74059d0080d8743421c65f9a/src/main/java/mops/presentation/FileController.java#L102

Isn't that a dataflow violation. Wouldn't
```java
Directory dir;
```
do the trick?

**Comment by kosch104** [comment]
Yes - if I remember correctly there are warnings when using a "not-initialized" variable, which is why we default set it to null.
