### ISSUE TITLE
Garbage Collector

### ISSUE THREAD

**Issue by realemx** [hhu-propra2/abschlussprojekt-mopse#181]
- [x] Should remove orphaned Files or FileInfos. 

- [x] Check if a group still exist. If not: delete all files and directories from the group. [Can use deleteService.deleteFolder]

**Comment by realemx** [comment]
To collect all the files, all the services need methods without permission checking, which isn't really elegant. Maybe we could change our restrictions and make the garbage collector a "special" component which can access all repositories by itlself? 
@iTitus @KaFe23 @Segelzwerg

**Comment by Segelzwerg** [comment]
I don't know if it's practical but we could add a role called `wallie` who is allowed everything everywhere.

**Comment by iTitus** [comment]
We don't need to add a new role, just create an account in the Garbage Collector class with the `admin` role (`@Value("mops.material1.role.admin")` or smth like that) and a name that makes it clear that it is an automated action happening (like `[GARBAGE_COLLECTOR]`)

**Comment by realemx** [comment]
Does not work: We don't check Keycloak roles. We fetch the role of a user in a directory. And a user named "Garbage Collector" isn't in any group so it never has any permissions.
