### ISSUE TITLE
MinIO Test Server

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#200]

**Comment by iTitus** [comment]
When deploying to heroku we need to host the needed MinIO instance somewhere. MariaDB can hopefully get hosted by heroku.
If we self-host on some web server we can use docker to start MariaDB and the MinIO instance

**Comment by Segelzwerg** [comment]
https://elements.heroku.com/addons/jawsdb-maria seems it does work

**Comment by iTitus** [comment]
No server from AWS, must either self-host or not
