### ISSUE TITLE
MinIO Data for local dev needed to be ignored

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#203]
![image](https://user-images.githubusercontent.com/25705862/77003090-fbc32780-695c-11ea-9c2a-0c6187639bf2.png)

**Comment by iTitus** [comment]
Just _delete_ the folder

**Comment by Segelzwerg** [comment]
well yes but generated stuff should be in gitignore

**Comment by iTitus** [comment]
it cannot be generated. just remove it

**Comment by Segelzwerg** [comment]
by why is generated at my machine. it was not there before running dev.

**Comment by iTitus** [comment]
pull master, remove it and run dev again. it should not be generated. if it is that would be a bug.

**Comment by Segelzwerg** [comment]
> pull master, remove it and run dev again. it should not be generated. if it is that would be a bug.

that did it
