### ISSUE TITLE
move classes

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#229]
- [x] FileRepositoryConfig should be in mops.persistence.config

- [x] StorageException should be in mops.persistence.exception

- [x] GruppenFindungExceotion should be in mops.businesslogic.exception

- [x] Services and related classes should be in own packages (for example mops.businesslogic.directory or mops.businesslogic.file)

**Comment by KaFe23** [comment]
This seems to be done by #237 and #238
