### ISSUE TITLE
Documentation: docker

### ISSUE THREAD

**Issue by iTitus** [hhu-propra2/abschlussprojekt-mopse#24]
Explain the environment variables and parameters needed to run the container.

**Comment by iTitus** [comment]
`MATERIAL1_DB_PORT`: (default: 23306) port for the MariaDB
`MATERIAL1_PORT`: (default: 8080) port for the application

Needed in the `prod.env` file, as seen in `prod-template.env`:
`MYSQL_ROOT_PASSWORD`: root password for MariaDB
`MYSQL_DATABASE`: ddatabase name

**Comment by Segelzwerg** [comment]
This is done by #199 isn't it @iTitus

**Comment by iTitus** [comment]
We didn't really describe what these environment variables mean and where they are used.
