### ISSUE TITLE
Wrong error message for creating folder with the same name

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#246]

**Comment by realemx** [comment]
![grafik](https://user-images.githubusercontent.com/49307158/77309498-10a50f80-6cfd-11ea-9508-5cc920e8da1c.png)

**Comment by Thabb** [comment]
Doesn't this come from the way a http post-request is handled? If the object already exists, post becomes just an update, or am I wrong?

**Comment by iTitus** [comment]
nope caused by typo in DirectoryServiceImpl: https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/master/src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java#L233-L234

**Comment by iTitus** [comment]
Closed by #265
