### ISSUE TITLE
Error Message in English

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#300]
![image](https://user-images.githubusercontent.com/25705862/77630976-37a55080-6f4c-11ea-9434-df7ec2980f36.png)

When creating a new directory without name. The error message is in English but should be in German.

**EDIT:** my machine location is English-US. It seems on German machines it's in German.

**Comment by iTitus** [comment]
dependent on browser locale
working as intended
