### ISSUE TITLE
Max Download Size must be infinity

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#346]
https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/bce0bb223da3757008fda6fe6b9996f000daaf5e/src/main/resources/application.properties#L39

It cannot be the same as the max upload size, because otherwise the zip download is broken. Image two max sized files are requested to be downloaded in one zip.

**Comment by iTitus** [comment]
kinda makes sense, did you actually test tho?

**Comment by Segelzwerg** [comment]
> kinda makes sense, did you actually test tho?

no, but I have a feeling this is the one time the application properties do work.

**Comment by Segelzwerg** [comment]
I was able to download a zip file with a size of 13.9 MB.

**Comment by iTitus** [comment]
It's request size, which is the size of the request the client sends. The server only sends responses.
