### ISSUE TITLE
Implement File Controller 

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#60]
`GET` Anfrage auf eine Datei (`material1/file/{file_id}`)

* Group ID irrelevant, da Zugriff auf einzelne Datei
* Content-Type Preview, z.B. PDF (Video player etc. optional)

`DELETE` Löschen einer Datei (`material1/file/{file_id}`)

**Comment by kosch104** [comment]
Basic FileController implemented and FileService delete and get added - TODO: Finish Controller when minIO logic is ready.
