### ISSUE TITLE
Implement GroupService

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#69]
Add a method that returns all root directories of all the groups the user is in it.

Also remove mock bean from:

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/39a25c913ecabd5aad5c7eed3444541a1e3a7e2f/src/test/java/mops/SecurityTests.java#L24-L28

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/39a25c913ecabd5aad5c7eed3444541a1e3a7e2f/src/test/java/mops/Material1ApplicationTests.java#L11-L15

and replace mock bean with implementation

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/39a25c913ecabd5aad5c7eed3444541a1e3a7e2f/src/test/java/mops/presentation/GroupsControllerTest.java#L41-L45

**Comment by iTitus** [comment]
Related to #40
