### ISSUE TITLE
Implement DirectoryService

### ISSUE THREAD

**Issue by ali3654** [hhu-propra2/abschlussprojekt-mopse#76]

**Comment by Segelzwerg** [comment]
In #92 I added the following interface:

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/b8eda92d0763cbab67b3de46835e357323ee7552/src/main/java/mops/businesslogic/DirectoryService.java#L8-L54

**Comment by iTitus** [comment]
The signature of uploadFile also needs to somehow take the actual file data. @realemx  knows how.

**Comment by Segelzwerg** [comment]
> The signature of uploadFile also needs to somehow take the actual file data. @realemx knows how.

I think this is a `java.nio.file.Files`, isn't it?
