### ISSUE TITLE
Implement FileInfoService

### ISSUE THREAD

**Issue by ali3654** [hhu-propra2/abschlussprojekt-mopse#78]

**Comment by Segelzwerg** [comment]
I called in my PR #80 FileService, shall I change it?

**Comment by Segelzwerg** [comment]
In #80 I added the following methods to the interface:

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/b8eda92d0763cbab67b3de46835e357323ee7552/src/main/java/mops/businesslogic/FileService.java#L10-L27

and in #92 these:

https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/b8eda92d0763cbab67b3de46835e357323ee7552/src/main/java/mops/businesslogic/FileService.java#L29-L34

**Comment by iTitus** [comment]
The IDs are all `long`s.

**Comment by Segelzwerg** [comment]
> The IDs are all `long`s.

changed it for #92 and for the rest in #93

**Comment by realemx** [comment]
It should be called FileService, as it interacts with the StorageService, DirService and GroupService to ensure all handling with Files and not just the Meta Objects.
